version: '3.7'

services:
  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: database-password
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nestjs.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin-password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8000:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db
